export const projectsData = [
  {
    id: 1,
    slug: "bug-tracking-website",
    src: "/images/projects/bugTracker.jpg",
    category: "Bug",
    title: "Bug Tracking website",
    year: "2025",
    company: "Zaky Soft pvt ltd",
    services: "Web Development",
    project: "Bug Tracking System",
    stack: ["REACT", "TAILWIND", "MYSQL", "DRIZZLE ORM"],
    description:
      "An internal bug and issue reporting system designed for company employees to report problems with detailed descriptions and file attachments. All reports are automatically synchronized with Jira and include real-time chat between users and administrators for faster resolution.",
    gallery: [
      "/images/projects/bugtracker/bug-tracker-ui.png",
      "/images/projects/bugtracker/bu-tracker-ui2.png",
      "/images/projects/bugtracker/bu-tracker-ui3.png",
      "/images/projects/bugtracker/bu-tracker-ui4.png",
      "/images/projects/bugtracker/bu-tracker-ui5.png",
    ],
  },
  {
    id: 2,
    slug: "client-dashboard",
    src: "/images/projects/dashboard.jpg",
    category: "Dashboard",
    title: "Client side Dashboard",
    year: "2025",
    company: "Zaky Soft pvt ltd",
    services: "Web Development",
    project: "Client Dashboard",
    stack: ["NEXT JS", "SHADCN", "TANSTACK QUERY", "NUQS", "LARAVEL", "MYSQL"],
    description:
      "A client-facing dashboard that visualizes business data, task status, and user activity in a clean and responsive interface with role-based access and performance-focused UI design.",
    gallery: [
      "/images/projects/client-dashboard/dashboard-1.png",
      "/images/projects/client-dashboard/dashboard-2.png",
      "/images/projects/client-dashboard/dashboard-3.png",
      "/images/projects/client-dashboard/dashboard-4.png",
    ],
  },
  {
    id: 3,
    slug: "brand-identity-motion-design",
    src: "/images/projects/partners-portal/image1.png",
    category: "PORTAL",
    title: "Partners Portal",
    year: "2024",
    company: "Personal Project",
    services: "Web Development",
    project: "Partners Portal",
    stack: ["REACT", "INERTIA", "MYSQL", "NUQS", "TANSTACK QUERY"],
    description:
      "A creative branding and motion design project focused on visual identity, animations, and consistent design systems across digital platforms.",
    gallery: [
      "/images/projects/partners-portal/image1.png",
      "/images/projects/partners-portal/image2.png",
      "/images/projects/partners-portal/image3.png",
      "/images/projects/partners-portal/image4.png",
      "/images/projects/partners-portal/image5.png",
      "/images/projects/partners-portal/image6.png",
      "/images/projects/partners-portal/image7.png",
      "/images/projects/partners-portal/image8.png",
      "/images/projects/partners-portal/image9.png",
      "/images/projects/partners-portal/image10.png",
      "/images/projects/partners-portal/image11.png",
      "/images/projects/partners-portal/image12.png",
    ],
  },
  {
    id: 4,
    slug: "mobile-application-design",
    src: "/images/projects/events/event1.png",
    category: "EVENTS",
    title: "Even booking Platform",
    year: "2024",
    company: "Personal Project",
    services: "UI / UX Design",
    project: "Event Booking Platform",
    stack: ["REACT", "NODE JS", "MONGODB", "TAILWIND"],
    description:
      "A mobile application UI design focused on usability, accessibility, and modern mobile interaction patterns.",
    gallery: [
      "/images/projects/events/event1.png",
      "/images/projects/events/event2.png",
      "/images/projects/events/event3.png",
      "/images/projects/events/event4.png",
      "/images/projects/events/event5.png",
      "/images/projects/events/event6.png",
      "/images/projects/events/event7.png",
      "/images/projects/events/event8.png",
      "/images/projects/events/event9.png",
      "/images/projects/events/event10.png",
      "/images/projects/events/event11.png",
    ],
  },
];
