export const skillsData = [
  { id: 1, name: "HTML", icon: "devicon-html5-plain colored" },
  { id: 2, name: "CSS", icon: "devicon-css3-plain colored" },
  { id: 3, name: "JavaScript", icon: "devicon-javascript-plain colored" },
  { id: 4, name: "React", icon: "devicon-react-original colored" },
  { id: 5, name: "Next.js", icon: "devicon-nextjs-original" },
  { id: 6, name: "Node.js", icon: "devicon-nodejs-plain colored" },
  { id: 7, name: "Express", icon: "devicon-express-original" },
  { id: 8, name: "MongoDB", icon: "devicon-mongodb-plain colored" },
  { id: 9, name: "MySQL", icon: "devicon-mysql-plain colored" },
  { id: 10, name: "Redux", icon: "devicon-redux-original colored" },
  { id: 11, name: "Git", icon: "devicon-git-plain colored" },
  { id: 12, name: "Tailwind", icon: "devicon-tailwindcss-original colored" },
  { id: 13, name: "Bootstrap", icon: "devicon-bootstrap-plain colored" },
  { id: 14, name: "AWS", icon: "devicon-amazonwebservices-original colored" },
  { id: 15, name: "Postman", icon: "devicon-postman-plain colored" },
  { id: 16, name: "Redux", icon: "devicon-redux-original colored" },
  { id: 17, name: "Context API", icon: "devicon-react-plain colored" },
  { id: 17, name: "Context API", icon: "devicon-react-plain colored" },
];
